<?php

/**
 *This Module provides a block list of all modules installed.
 *
 * Implements hook_menu().
 *
 */
function modlist_block_info() {

  $blocks = array();
  $blocks['list_modules'] = array(
  		'info' => t('A list of all enebled modules'),
      'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/** Implement hook_block_view*/

function modlist_block_view($block_name =''){
  if($block_name == 'list_modules'){
  $list = module_list();

 $theme_args = array('items' => $list, 'type' => 'ol');
 $content = theme('item_list', $theme_args);

 $block = array(
 'subject' => t('Enabled Modules'),
 'content' => $content,
 );
 return $block;
  }
}
