<?php

/**
 * implements hook_menu()
 */
function owner_menu(){ 
  $items  = array();
  $items['Owner'] = array(

    'title' => "Site Owner",
    'page callback' => "owner_info", 
    'access callback' => true,

    'type' => MENU_NORMAL_ITEM, // drupal's default menu type 
    'weight' => '10', // to display member link below in our nav menu
  );    
    return $items; // finally, return items
}

/**
 * callback function for owner
 *
 */
function owner_info(){
  $output = 'Name: Eucheria </br>';
  $output .= 'Gender: female</br>';
  $output .= 'Age: askme.com</br>';
  $output .= 'City: Copenhagen </br>';
  $output .= 'Country: Denmark</br>';
  return $output;
}